### ISSUE TITLE
reduce visual weight of website

### ISSUE THREAD

**Issue by gjwehnes** [thirstyice/abe-site#103]
-Black lines on LHS / RHS menu items to be reduced or eliminated (this will require some discussion on what is optimal)
-Background to be changed to an off-white (solid colour, or a subtle pattern such as Western HS's website)

**Comment by kid47** [comment]
Is this coming from admin all of a sudden? And I thought that we were already breaking the rules by using a secondary colour for the background, will it be alright if we use a colour that isn't listed?

**Comment by kid47** [comment]
![menunoborder](https://cloud.githubusercontent.com/assets/8888679/5949995/86b3af54-a711-11e4-9438-dc54a9ccd321.PNG)
How's this?

**Comment by thirstyice** [comment]
As above, why the about-face? The website has been up for nearly a year now, people are getting used to the look we have, why do we need to make a change and risk people getting angry again? Plus it's not as simple as just removing the lines, the whole design would have to be redone so that all the elements work together again.

**Comment by gjwehnes** [comment]
I appreciate the honest thoughts. Please keep in mind:
1. We are not (at this point) redesigning, we are tweaking. The background is not actually part of our website. To be clear, we are talking about the outside background (currently medium-grey with the ABE "A" tiled across it), not the site's background (which will remain white)
2. This is not an about-face. Websites are living documents, and they evolve. In this case, we are responding to end user feedback. This request has come to me from Mr. Fournier, who bases it on feedback that he receives directly from parents and from teachers.
3. We do not own this website. The CBE technically owns it, and all parents, teachers, and students are stakeholders. As developers, we ultimately have to respond to what our client (i.e. The CBE, through WAHS's admin team) would like to have. Trust me, I know firsthand that as a developer you start to feel quite strongly about your product, and it is difficult sometimes to be asked to change a part of it for your client. Especially when you don't necessarily agree with the change. However, they "write the cheque" as it were, and not responding to a client's wish is not particularly good business.

**Comment by gjwehnes** [comment]
Let's go with what kid47 has proposed for the menus. For the outside background, either a small-scale pattern or a solid colour, let's experiment a bit with it.

**Comment by kid47** [comment]
1. I didn't know the outside background was no longer considered part of the site, which was a misunderstanding on my part. I apologize.
2 & 3. I understand the changes and don't mind implementing them, in fact, I very much want to implement them since it's coming from feedback. It's more that we haven't heard this specific feedback through the communication lines that we've been monitoring, i.e. the website survey and github, until now and hadn't heard anything coming from elsewhere. The problem that we were trying to solve with these was communication with the user and the client to improve their experience and overall satisfaction and so, had they let us known that feedback was coming in, we would have been more than happy to work with it. I believe I speak for both of us when I say "about-face" was not quite the right way to say that we've not heard much from other sources for a while, and so we were surprised at the sudden requests for changes when there have been attempts to create ongoing discussions, like issues #83 and #97, to solve issues related to this.

**Comment by thirstyice** [comment]
As @kid47 said, about-face was not quite the wording I was looking for.

Though the CBE may own the content of the website, the design belongs to me, and the copyright is very clear on that point. That being said, the users have spoken, and if they want no lines, then no lines they will have, but I would like to make the modifications myself so that I know we aren't just changing elements without considering the design overall.

**Comment by thirstyice** [comment]
Rather than changing the background we could implement auto-resizing content. The only thing stopping us is the abe banner, and we have discussed removing that to make room for a search bar. Perhaps both could be done at once?

**Comment by thirstyice** [comment]
Ok, it still has lines, but the weight is definitely less than before.

**Comment by gjwehnes** [comment]
We can discuss further where this site is going when we meet again in person next week. Things will be easier going forward because we will be direct contact. This is why developer teams still meet.

Point taken about the communication. Part of my role is to act as a buffer between the development team and admin. A great many requests for addition / modification to our website have not made it to our issues list because they were impractical or in direct contradiction of our guidelines and layout principals.

The copyright question is interesting. Two points to ponder here:
1) My understanding is that the CBE has a clause within their use of electronic resources contract (which we all have signed) which stipulates that any and all work created on CBE equipment automatically becomes property of the board. I cannot say if the same is true for any work hosted on a CBE server, but I would guess that this is covered as well.
2) Most companies and/or clients will do the same. They will ask their employees to sign a waiver releasing any claim to ownership of intellectual property. This is usually done as part of contract negotiations. I have kept lots of code from my days as a programmer, but doing so is technically illegal!

The world is ofcourse evolving and our legal system is still trying to figure all of this out, but for now, it would be safe to say that none of us actually have any legal claim (despite any copyright notices we may have added).

What we own (and what is truly valuable) are the skills and the experience.

**Comment by gjwehnes** [comment]
As of commit af80edaa25dae95160fb4002242a96f63ceeb70a, the line weight on the right hand side menu has not yet been changed

![visual weight](https://cloud.githubusercontent.com/assets/6045608/5982759/b54d1e40-a883-11e4-8605-09393b04c5f5.jpg)

**Comment by kid47** [comment]
This is what it looks like for me:
![menunoborder](https://cloud.githubusercontent.com/assets/8888679/5985480/00eca0ca-a8a0-11e4-8fd5-d2817d938b11.PNG)
Maybe it's been cached by chrome?

**Comment by kid47** [comment]
I feel like now that we've done this, we should also reduce the weight of the border for #border, as it's the only thing left with the thick black

**Comment by kid47** [comment]
How's this for the new background colour?
![alternatebackground](https://cloud.githubusercontent.com/assets/8888679/5986057/52e73890-a8aa-11e4-80b1-2a471b010327.PNG)

**Comment by thirstyice** [comment]
As I said above, I think it would be best to have auto-resizing content, is which case the border and background colour would be irrelevant.

**Comment by kid47** [comment]
Actually, in new-new-ui we still have the border with resizable content. Plus it would take a while to test and implement, so this is more like a transition

**Comment by thirstyice** [comment]
I've been working on this gradually for a year. As it stands, there is one class that limits the width of our website, and the resizing (or not) of the content has nothing to do with the border.

**Comment by kid47** [comment]
I know, but that would be classified as a major change, and so we'll want to clear it with people first. 

And it doesn't really to us, but if we're going to make ui changes, we'll want to take it slow so that we don't get complaints from the users as the would just group it all together as 'a change'. I think, therefore, we should implement the change that's been approved first, and then give ourselves some time to beta test the dynamic layout in a different branch while we let people get used to the new ui before we implement the more drastic change. 

We may also want to have a discussion about minimum and maximum width of a dynamic layout as well as the effects on the banner.

**Comment by thirstyice** [comment]
Minimum width is 960px, smaller than that and the topmenu doesn't fit. As I said above, the banner will have to be removed.
How do you propose we slowly implement resizing content? Dial up the maximum size one pixel at a time?

**Comment by kid47** [comment]
OK, sounds good. And I didn't mean the one commit, I meant that we should slowly roll out the multiple ui changes, as in do one change this week, and then a couple of weeks down the road from now do the dynamic layout

**Comment by thirstyice** [comment]
Ok. Shall we implement resizing content for Saint Valentine's day then?

**Comment by kid47** [comment]
Sounds good to me. We'll have to put this past @gjwehnes tomorrow though

**Comment by thirstyice** [comment]
#104 Sometime in between now and then?

**Comment by kid47** [comment]
Same thing, sounds good to me, but ultimately we have to put it past @gjwehnes because he has the permissions to the server

**Comment by thirstyice** [comment]
And the search bar?

**Comment by kid47** [comment]
I think we could do that at the same time as #104. Are we going to want to approve the other pull requests as well, like the FAQ?

**Comment by thirstyice** [comment]
I don't think so. We're more looking at ui changes rather than content, and the banner being removed precludes having one that rotates.

**Comment by kid47** [comment]
On a tangent: How's this for the alternate background colour?
![alternatebackground](https://cloud.githubusercontent.com/assets/8888679/5993874/d4096958-aa1b-11e4-956a-42653bff17d6.PNG)

It'll probably be made moot by implementing a dynamic layout, but for the time being it'll do.

**Comment by thirstyice** [comment]
I thought this wasn't happening. Was there not a whole discussion about the best time to make this not happen?

**Comment by kid47** [comment]
I thought we were still running with it. Either way, it was just a test

**Comment by thirstyice** [comment]
Resizing contend implemented in 9437555a5bd066bd3989219051943b0dbb4af976
All done here

**Comment by kid47** [comment]
Min width should be 935px, otherwise "about us" gets cut off and partially wrapped.

**Comment by thirstyice** [comment]
This should have been a new issue, but done
