### ISSUE TITLE
"External link" not external

### ISSUE THREAD

**Issue by thirstyice** [thirstyice/abe-site#106]
The link in the External links section entitled "Finding your Gmail address" is not an external link, and needs to be moved or removed.

**Comment by gjwehnes** [comment]
The location for this link is not fixed, and I would welcome suggestions for other locations.

It was placed in its current location because it is very closely related to the two external links directly above it. Unfortunately, those two links do not do a very good job of explaining to students how to obtain their @educbe gmail address.

**Comment by thirstyice** [comment]
The ongoing news section, with the homelogic parent letter.

**Comment by kid47** [comment]
How about we just rename the right side to quick links and then add (external) to the ones that are external

**Comment by thirstyice** [comment]
That is what we were specifically trying to avoid when the website was built. We made a place that was exclusively for external links.

**Comment by kid47** [comment]
Things change however. We have a few things that could have gone there since we made the website. The search bar helps, but otherwise I think it could improve usability
