### ISSUE TITLE
PDF viewer not working correctly in IE

### ISSUE THREAD

**Issue by gjwehnes** [thirstyice/abe-site#150]
iFrame shows up as empty

This appears to be happening for all PDFs; buttons on iFrame are functional.

URL: http://localhost/b829/aberhart/universal/pdf/web/viewer.html?file=/b829/aberhart/main/exams/exam-schedule.pdf
version 9.0.8112

**Comment by kid47** [comment]
![image](https://cloud.githubusercontent.com/assets/8888679/7713019/1341c902-fe32-11e4-8bbb-a815cb116c4e.png)
This is the error being thrown by IE when this is happening. We probably have a little bit of a grace period as only about 16% (plus standard deviation) of our user base is using IE, and this doesn't seem to be an issue with the newest version (though that probably should be confirmed again in case I missed something), so most of our users will not be affected. 

From the error, it seems that the problem is not on our side, but on PDF.js' side, so unfortunately the only solution may be to eventually roll this back so that we're using the old method. Either that or we force our users to either update IE or move to an alternate browser

**Comment by thirstyice** [comment]
What is your source for the 16%?
There is no old method to roll back to.
We don't use iframes anymore, so we should really stop calling them iframes.
Could replicate on IE 11, Windows 8, with IE 9 mode enabled.
Looking into it.

**Comment by thirstyice** [comment]
This arises because we (I) removed the "open external file" button because it is useless to us.
Most browsers just deal with that missing element, but not IE.

**Comment by kid47** [comment]
Source for the 16% is from our website survey
