### ISSUE TITLE
French immersion department pdf

### ISSUE THREAD

**Issue by thirstyice** [thirstyice/abe-site#66]
This pdf has so many issues.
* ~~Links to external files in such a way that they will be imported into our iframe~~ (Won't happen any more because of #109)
* Links to pdf documents without using the pdf wrapper
* Includes a word document which, as far as I can tell, is not accessible by website navigation
* Includes a word document, a document which cannot be opened by any web browser  
~~This pdf will cause a revival of issues #19 and #25~~ (Won't happen any more because of #109)

For this amount of information and links, I recommend re-writing this pdf as either one or several web pages

**Comment by gjwehnes** [comment]
Having teaching staff developing their own web pages would be ideal but not realistic at this point.

Unfortunately the current set-up (very detailed PDFs with embedded links all over the place) was introduced some years ago, and the page has become fossilized. The documents in question are widely distributed outside of our website, and the links are relied upon to provide secondary information. e.g. the departments/french/immersion.pdf document is often used in presentations to parents, or sent out via email as a single attachment.

All that said, I will approach the content owner and discuss bringing the format into line, because it is also a maintainance issue.

**Comment by kid47** [comment]
This hasn't been touched in ages so I'm marking it as a wontfix

**Comment by thirstyice** [comment]
The PDF Guideline violation label was meant to convey the inability to fix the issue, but in this case I agree

**Comment by thirstyice** [comment]
This closed automatically when I merged #149, which is really cool, but I don't know why or how.
